package quiz89.example.quiz;

public class Array2 {

    //начало массива первого уровня
    final int [] images = {
            R.drawable.twolevel_one,
            R.drawable.twolevel_two,
            R.drawable.twolevel_free,
            R.drawable.twolevel_four,
            R.drawable.twolevel_fife,
            R.drawable.twolevel_six,
            R.drawable.twolevel_seven,
            R.drawable.twolevel_eight,
            R.drawable.twolevel_nine,
            R.drawable.twolevel_ten,
    };


    final int [] text1 = {
            R.string.level2text0,
            R.string.level2text1,
            R.string.level2text2,
            R.string.level2text3,
            R.string.level2text4,
            R.string.level2text5,
            R.string.level2text6,
            R.string.level2text7,
            R.string.level2text9,
            R.string.level2text10,
    };
    final int [] images3 = {
            R.drawable.freelevel_apple,
            R.drawable.freelevel_astonavt,
            R.drawable.freelevel_banana,
            R.drawable.freelevel_car,
            R.drawable.freelevel_cande,
            R.drawable.freelevel_home,
            R.drawable.freelevel_mango,
            R.drawable.freelevel_mars,
            R.drawable.freelevel_cherry,
            R.drawable.freelevel_satern,
            R.drawable.freelevel_cok,
            R.drawable.freelevel_most,
            R.drawable.freelevel_orange,
            R.drawable.freelevel_poezd,
            R.drawable.freelevel_steik,
            R.drawable.freelevel_racettkafortenis,
            R.drawable.freelevel_strawberry,
            R.drawable.freelevel_rocket,
            R.drawable.freelevel_waterlevel,
            R.drawable.frelevel_tover,
    };
    final int [] text2 = {
            R.string.level3text0,
            R.string.level3text1,
            R.string.level3text2,
            R.string.level3text3,
            R.string.level3text4,
            R.string.level3text5,
            R.string.level3text6,
            R.string.level3text7,
            R.string.level3text8,
            R.string.level3text9,
            R.string.level3text10,
            R.string.level3text11,
            R.string.level3text12,
            R.string.level3text13,
            R.string.level3text14,
            R.string.level3text15,
            R.string.level3text16,
            R.string.level3text17,
            R.string.level3text18,
            R.string.level3text19,


    };
    final int [] oneTwo = {
            0,
            1,
            0,
            1,
            0,
            1,
            0,
            1,
            0,
            1,
            0,
            1,
            0,
            1,
            0,
            1,
            0,
            1,
            0,
            1,

    };


    //начало массива четвертого уровня уровня
    final int [] images4 = {
            R.drawable.fourlevel_one,
            R.drawable.fourlevel_two,
            R.drawable.fourlevel_free,
            R.drawable.fourlevel_four,
            R.drawable.fourlevel_fifie,
            R.drawable.fourlevel_six,
            R.drawable.fourlevel_seven,
            R.drawable.fourlevel_eight,
            R.drawable.fourlevel_nine,
            R.drawable.fourlevel_ten,
    };
    final int [] text4 = {
            R.string.level4text0,
            R.string.level4text1,
            R.string.level4text2,
            R.string.level4text3,
            R.string.level4text4,
            R.string.level4text5,
            R.string.level4text6,
            R.string.level4text7,
            R.string.level4text8,
            R.string.level4text9,

    };

    final int [] images5 = {
            R.drawable.fifelevel_one,
            R.drawable.fifelevel_two,
            R.drawable.fifelevel_free,
            R.drawable.fifelevel_four,
            R.drawable.fifelevel_fife,
            R.drawable.fifelevel_six,
            R.drawable.fifelevel_seven,
            R.drawable.fifelevel_eight,
            R.drawable.fifelevel_nine,
            R.drawable.fifelevel_ten,
    };
    final int [] text5 = {
            R.string.level5text0,
            R.string.level5text1,
            R.string.level5text2,
            R.string.level5text3,
            R.string.level5text4,
            R.string.level5text5,
            R.string.level5text6,
            R.string.level5text7,
            R.string.level5text8,
            R.string.level5text9,

    };
    final int [] images6 = {
            R.drawable.sixlevel_one,
            R.drawable.sixlevel_two,
            R.drawable.sixlevel_free,
            R.drawable.sixlevel_four,
            R.drawable.sixlevel_fife,
            R.drawable.sixlevel_six,
            R.drawable.sixlevel_eight,
            R.drawable.sixlevel_nine,
            R.drawable.sixlevel_ten,
            R.drawable.sixlevel_eleven,
            R.drawable.sixlevel_twelve,
            R.drawable.sixlevel_thirteen,
            R.drawable.sixlevel_fourteen,
            R.drawable.sixlevel_fifeteen,
            R.drawable.sixlevel_sixteen,
            R.drawable.sixlevel_seventeen,
            R.drawable.sixlevel_eigteen,
            R.drawable.sixlevel_nineteen,
    };
    final int [] text6 = {
            R.string.level6text0,
            R.string.level6text1,
            R.string.level6text2,
            R.string.level6text3,
            R.string.level6text4,
            R.string.level6text5,
            R.string.level6text6,
            R.string.level6text7,
            R.string.level6text8,
            R.string.level6text9,
            R.string.level6text10,
            R.string.level6text11,
            R.string.level6text12,
            R.string.level6text13,
            R.string.level6text14,
            R.string.level6text15,
            R.string.level6text16,
            R.string.level6text17,
    };
    final int [] images7 = {
            R.drawable.sevenlevel_one,
            R.drawable.sevenlevel_two,
            R.drawable.sevenlevel_three,
            R.drawable.sevenlevel_four,
            R.drawable.sevenlevel_fife,
            R.drawable.sevenlevel_six,
            R.drawable.sevenlevel_seven,
            R.drawable.sevenlevel_eight,
            R.drawable.sevenlevel_nine,
            R.drawable.sevenlevel_ten,
            R.drawable.sevenlevel_elevn,
            R.drawable.sevenlevel_twelv,
            R.drawable.sevenlevel_thirteen,
            R.drawable.sevenlevel_fourteen,
            R.drawable.sevenlevel_fifeteen,
            R.drawable.sevenlevel_sixteen,
    };

    final int [] text7 = {
            R.string.level7text0,
            R.string.level7text1,
            R.string.level7text2,
            R.string.level7text3,
            R.string.level7text4,
            R.string.level7text5,
            R.string.level7text6,
            R.string.level7text7,
            R.string.level7text8,
            R.string.level7text9,
            R.string.level7text10,
            R.string.level7text11,
            R.string.level7text12,
            R.string.level7text13,
            R.string.level7text14,
            R.string.level7text15,
    };

    final int [] level8oneTwo = {
            0,
            1,
            0,
            1,
            0,
            1,
            0,
            1,
            0,
            1,
            0,
            1,
            0,
            1,
            0,
            1,
            0,
            1,
            0,
            1,
    };

    final int [] images8 = {
            R.drawable.eightlevel_apple,
            R.drawable.eightlevel_tomato,
            R.drawable.eightlevel_cherry,
            R.drawable.eightlevel_blackberry,
            R.drawable.eightlevel_banana,
            R.drawable.eightlevel_strawberry,
            R.drawable.eightlevel_kokos,
            R.drawable.eghtlevel_watermelon,
            R.drawable.eightlevel_limon,
            R.drawable.eightlevel_cucumber,
            R.drawable.eightlevel_pear,
            R.drawable.eightlevel_pepper,
            R.drawable.eightlevel_laim,
            R.drawable.eightlevel_marking,
            R.drawable.eightlevel_mango,
            R.drawable.eightlevel_onion,
            R.drawable.eightlevel_peach,
            R.drawable.eightlevel_grape,
            R.drawable.eightlevel_plum,
            R.drawable.eightlevel_mushrooms,
    };

    final int [] text8 = {
            R.string.level8text0,
            R.string.level8text1,
            R.string.level8text2,
            R.string.level8text3,
            R.string.level8text4,
            R.string.level8text5,
            R.string.level8text6,
            R.string.level8text7,
            R.string.level8text8,
            R.string.level8text9,
            R.string.level8text10,
            R.string.level8text11,
            R.string.level8text12,
            R.string.level8text13,
            R.string.level8text14,
            R.string.level8text15,
            R.string.level8text16,
            R.string.level8text17,
            R.string.level8text18,
            R.string.level8text19,
    };

    final int [] images9 = {
            R.drawable.ninelevel_one,
            R.drawable.ninelevel_two,
            R.drawable.ninelevel_three,
            R.drawable.ninelevel_four,
            R.drawable.ninelevel_fife,
            R.drawable.ninelevel_six,
            R.drawable.ninelevel_seven,
            R.drawable.ninelevel_eight,
            R.drawable.ninelevel_nine,
            R.drawable.ninelevel_ten,
    };

    final int [] text9 = {
            R.string.level9text0,
            R.string.level9text1,
            R.string.level9text2,
            R.string.level9text3,
            R.string.level9text4,
            R.string.level9text5,
            R.string.level9text6,
            R.string.level9text7,
            R.string.level9text8,
            R.string.level9text9,
    };
    final int [] images10 = {
            R.drawable.tenlevel_zero,
            R.drawable.tenlevel_one,
            R.drawable.tenlevel_two,
            R.drawable.tenlevel_three,
            R.drawable.tenlevel_four,
            R.drawable.tenlevel_five,
            R.drawable.tenlevel_six,
            R.drawable.tenlevel_seven,
            R.drawable.tenlevel_eight,
            R.drawable.tenlevel_nine,
    };
    final int [] text10 = {
            R.string.level10text0,
            R.string.level10text1,
            R.string.level10text2,
            R.string.level10text3,
            R.string.level10text4,
            R.string.level10text5,
            R.string.level10text6,
            R.string.level10text7,
            R.string.level10text8,
            R.string.level10text9,
    };

    final int [] level11oneTwo = {
            0,
            1,
            0,
            1,
            0,
            1,
            0,
            1,
            0,
            1,
            0,
            1,
            0,
            1,
            0,
            1,
            0,
            1,
            0,
            1,
    };

    final int [] images11 = {
            R.drawable.leveleleven_iran,
            R.drawable.elevellevel_itali,
            R.drawable.leveleleven_japan,
            R.drawable.elevellevel_usa,
            R.drawable.leveleleven_kazah,
            R.drawable.elevenlevel_argentina,
            R.drawable.leveleleven_korea,
            R.drawable.elevenlevel_brazil,
            R.drawable.leveleleven_pakistan,
            R.drawable.elevenlevel_kanada,
            R.drawable.leveleleven_taivan,
            R.drawable.elevenlevel_meksika,
            R.drawable.leveleleven_thailand,
            R.drawable.elevenlevel_rasha,
            R.drawable.leveleleven_vietam,
            R.drawable.elevenlevel_ruminia,
            R.drawable.levelelven_armenia,
            R.drawable.elevenlevel_velokobritania,
            R.drawable.levelelven_mongolia,
            R.drawable.elevenlevel_ukr,

    };

    final int [] text11 = {
            R.string.level11text0,
            R.string.level11text1,
            R.string.level11text2,
            R.string.level11text3,
            R.string.level11text4,
            R.string.level11text5,
            R.string.level11text6,
            R.string.level11text7,
            R.string.level11text8,
            R.string.level11text9,
            R.string.level11text10,
            R.string.level11text11,
            R.string.level11text12,
            R.string.level11text13,
            R.string.level11text14,
            R.string.level11text15,
            R.string.level11text16,
            R.string.level11text17,
            R.string.level11text18,
            R.string.level11text19,
    };


}
